defaults:
  - tokenizer_modifier: bert
  - _self_

lm_mode: mlm
task_type: masked_lm

pretrained_model_name_or_path: bert-base-uncased
short_model_name: ${language_model.pretrained_model_name_or_path}