defaults:
  - tokenizer_modifier: bert
  - _self_

lm_mode: mlm
task_type: masked_lm
pretrained_model_name_or_path: ${paths.data_dir}/models/EmoLoop/required_files/dst/SentiX_Base_Model
manual_tokenizer_override_pretrained_model_name_or_path: bert-base-uncased

short_model_name: bert-base-uncased-SentiX
