lm_mode: MLM

pretrained_model_name_or_path: ${paths.data_dir}/models/finetuned_models/data-multiwoz21_split-train_ctxt-dataset_entry_samples-10000/model-bert-base-uncased/ftm-standard/lora-None/ep-5/model_files
short_model_name: bert-base-uncased_finetuned-on-multiwoz21_ftm-standard