checkpoint_no: 2800
lm_mode: clm
task_type: causal_lm
pretrained_model_name_or_path: ${paths.data_dir}/models/finetuned_models/data=multiwoz21_rm-empty=True_spl-mode=do_nothing_ctxt=dataset_entry_feat-col=ner_tags/split=train_samples=10000_sampling=take_first/model=gpt2-medium_task=causal_lm_dr=defaults/ftm=standard/lora-None/gradmod=do_nothing_target-freeze=/lr=5e-05_lr-scheduler-type=linear_wd=0.01/bs-train=8/ep=5/seed=1234/model_files/checkpoint-${language_model.checkpoint_no}
manual_tokenizer_override_pretrained_model_name_or_path: null
seed: 1234
short_model_name: gpt2-medium-causal_lm-defaults_multiwoz21-rm-empty-True-do_nothing-ner_tags_train-10000-take_first-111_standard-None_5e-05-linear-0.01-5_seed-${language_model.seed}_ckpt-${language_model.checkpoint_no}
dropout:
  mode: defaults
  probabilities:
    hidden_dropout_prob: 0.1
    attention_probs_dropout_prob: 0.1
    classifier_dropout: null
tokenizer_modifier:
  mode: add_padding_token
  padding_token: "<|pad|>"
