defaults:
  - tokenizer_modifier: gpt2
  - _self_

checkpoint_no: 2800
lm_mode: CLM
masking_mode: no_masking
pretrained_model_name_or_path: ${paths.data_dir}/models/finetuned_models/data-one-year-of-tsla-on-reddit_split-train_ctxt-dataset_entry_samples-10000/model-gpt2-medium/ftm-standard/lora-None/lr-5e-05_lr_scheduler_type-linear_wd-0.01/ep-5/model_files/checkpoint-${language_model.checkpoint_no}
short_model_name: gpt2-medium_finetuned-on-one-year-of-tsla-on-reddit_ftm-standard_checkpoint-${language_model.checkpoint_no}

