defaults:
  - tokenizer_modifier: do_nothing
  - _self_

lm_mode: clm
task_type: causal_lm

pretrained_model_name_or_path: ${paths.luster_repository_base_path}/data/model_checkpoints/luster-rl(succ)
short_model_name: luster-rl-succ