checkpoint_no: 0
lm_mode: mlm
task_type: masked_lm
pretrained_model_name_or_path: ${paths.data_dir}/models/finetuned_models/data-one-year-of-tsla-on-reddit_split-train_ctxt-dataset_entry_samples-80_feat-col-ner_tags/model-roberta-base_task-masked_lm/ftm-standard/lora-None/gradmod-do_nothing_target-freeze-/lr-5e-05_lr_scheduler_type-linear_wd-0.01/bs-train-16/ep-2/seed-${language_model.seed}/model_files/checkpoint-${language_model.checkpoint_no}
manual_tokenizer_override_pretrained_model_name_or_path: null
seed: 1236
short_model_name: model-roberta-base_task-masked_lm_one-year-of-tsla-on-reddit-train-80-ner_tags_ftm-standard_lora-None_5e-05-linear-0.01-2_seed-${language_model.seed}_ckpt-${language_model.checkpoint_no}
tokenizer_modifier:
  mode: do_nothing
  padding_token: <pad>
