checkpoint_no: 31200
lm_mode: MLM
task_type: MASKED_LM
pretrained_model_name_or_path: ${paths.data_dir}/models/finetuned_models/data-multiwoz21_split-train_ctxt-dataset_entry_samples-10000_feat-col-ner_tags/model-roberta-base_task-masked_lm/ftm-standard/lora-None/gradmod-do_nothing_target-freeze-/lr-5e-05_lr_scheduler_type-SchedulerType.CONSTANT_wd-0.01/bs-train-8/ep-50/model_files/checkpoint-${language_model.checkpoint_no}
short_model_name: model-roberta-base_task-masked_lm_multiwoz21-train-10000-ner_tags_ftm-standard_lora-None_5e-05-constant-0.01-50_ckpt-${language_model.checkpoint_no}
tokenizer_modifier:
  mode: DO_NOTHING
  padding_token: <pad>
