checkpoint_no: 1200
lm_mode: MLM
masking_mode: no_masking
pretrained_model_name_or_path: ${paths.data_dir}/models/finetuned_models/data-one-year-of-tsla-on-reddit_split-train_ctxt-dataset_entry_samples-10000/model-roberta-base/ftm-standard/lora-None/gradmod-do_nothing_target-freeze-/lr-5e-05_lr_scheduler_type-linear_wd-0.01/bs-train-16/ep-5/model_files/checkpoint-${language_model.checkpoint_no}
short_model_name: model-roberta-base_one-year-of-tsla-on-reddit-train-10000_ftm-standard_lora-None_5e-05-linear-0.01-5_ckpt-${language_model.checkpoint_no}
tokenizer_modifier:
  mode: DO_NOTHING
  padding_token: <pad>
