checkpoint_no: 2813
seed: 0
lm_mode: mlm
task_type: masked_lm
pretrained_model_name_or_path: ${paths.data_dir}/models/setsumbt_checkpoints/multiwoz21/roberta/setsumbt/gru/cosine/labelsmoothing/0.05/seed${language_model.seed}/04-09-2024-14-53/checkpoint-${language_model.checkpoint_no}

short_model_name: model-roberta-base_task-setsumbt_multiwoz21_seed-${language_model.seed}_ckpt-${language_model.checkpoint_no}
tokenizer_modifier:
  mode: do_nothing
  padding_token: <pad>
