defaults:
  - tokenizer_modifier: roberta
  - _self_

checkpoint_no: 8500 # according to the tensorboard logs, this has lowest validation loss on multiwoz21-validation
lm_mode: MLM
masking_mode: no_masking
pretrained_model_name_or_path: ${paths.data_dir}/models/finetuned_models/data-multiwoz21_split-train_ctxt-dataset_entry_samples--1/model-roberta-base/ftm-standard/lora-None/gradmod-do_nothing_target-freeze-[]/lr-5e-05_lr_scheduler_type-linear_wd-0.01/bs-train-32/ep-5/model_files/checkpoint-${language_model.checkpoint_no}
short_model_name: roberta-base_finetuned-on-multiwoz21_ftm-standard_full-dataset_checkpoint-${language_model.checkpoint_no}