defaults:
  - tokenizer_modifier: roberta
  - _self_

lm_mode: mlm

pretrained_model_name_or_path: ${paths.data_dir}/models/finetuned_models/data-multiwoz21_split-train_ctxt-dataset_entry_samples-10000/ftm-lora/r-16_alpha-32_lora-target-['query', 'key', 'value']_lora-dropout-0.01/ep-5/model_files
short_model_name: roberta-base_finetuned-on-multiwoz21_ftm-lora