pretrained_model_name_or_path: ${paths.data_dir}/models/finetuned_models/data-multiwoz21_split-train_ctxt-dataset_entry/ep-3/model_files
short_model_name: roberta-base_finetuned-on-multiwoz21-train-5000_context-utterance_ep-3
masking_mode: no_masking