lm_mode: MLM
masking_mode: no_masking
pretrained_model_name_or_path: roberta-base
short_model_name: ${language_model.pretrained_model_name_or_path}
tokenizer_modifier:
  mode: do_nothing
  padding_token: "<pad>"