lm_mode: MLM
masking_mode: no_masking
pretrained_model_name_or_path: ${paths.data_dir}/models/finetuned_models/data-multiwoz21_split-train_ctxt-dataset_entry_samples-10000/model-roberta-base/ftm-standard/lora-None/ep-15/model_files/checkpoint-1200
short_model_name: roberta-base_finetuned-on-multiwoz21_ftm-standard