defaults:
  - tokenizer_modifier: roberta
  - _self_

checkpoint_no: 31200
lm_mode: MLM
masking_mode: no_masking
pretrained_model_name_or_path: ${paths.data_dir}/models/finetuned_models/data-one-year-of-tsla-on-reddit_split-train_ctxt-dataset_entry_samples-10000/model-roberta-base/ftm-standard/lora-None/lr-5e-05_lr_scheduler_type-constant_wd-0.01/ep-50/model_files/checkpoint-${language_model.checkpoint_no}
short_model_name: roberta-base_finetuned-on-one-year-of-tsla-on-reddit_ftm-standard_overfitted_checkpoint-${language_model.checkpoint_no}