defaults:
  - _self_

method_description: "twonn"

compute_global_estimates: true

filtering:
  num_samples: 2500
  zero_vector_handling_mode: "keep"

pointwise:
  n_neighbors_mode: "relative_size"
  absolute_n_neighbors: 128
  relative_n_neighbors: 0.8
