train_dataset:
  column_name: text
  context: dataset_entry
  dataset_description_string: multiwoz21
  dataset_path: json
  dataset_name: multiwoz21
  data_dir: ${paths.data_dir}/datasets/dialogue_datasets/multiwoz21
  dataset_type: huggingface_dataset
  number_of_samples: 10000
  split: train
eval_dataset:
  column_name: text
  context: dataset_entry
  dataset_description_string: multiwoz21
  dataset_path: json
  dataset_name: multiwoz21
  data_dir: ${paths.data_dir}/datasets/dialogue_datasets/multiwoz21
  dataset_type: huggingface_dataset
  number_of_samples: 10000
  split: validation