defaults:
  - dataset_map: batched
  - embedding_extraction: last_hidden
  # - language_model: roberta-base
  - language_model: roberta-base_finetuned-on-multiwoz21-train
  # - language_model: roberta-base_finetuned-on-multiwoz21-train-and-sgd-train
  - tokenizer: basic_tokenizer
  - _self_

batch_size: 32
level: token
num_workers: 0