defaults:
  - dataset_map: batched
  - embedding_extraction: last_hidden
  # - language_model: roberta-base
  # - language_model: roberta-base_finetuned-on-multiwoz21-train_context-dialogue
  # - language_model: roberta-base_finetuned-on-multiwoz21-train-and-sgd-train_context-dialogue
  - language_model: roberta-base_finetuned-on-multiwoz21-train-5000_context-utterance_ep-3
  #- language_model: roberta-base_finetuned-on-multiwoz21-train-5000_context-utterance_ep-5
  - tokenizer: basic_tokenizer
  - _self_

batch_size: 32
level: token
num_workers: 0