defaults:
  - dataset_map: batched
  - tokenizer: basic_tokenizer
  - _self_

batch_size: 32
embedding_extraction:
  layer_indices: 
  - -1
  aggregation: mean
language_model:
  huggingface_model_name: roberta-base
  masking_mode: no_masking
level: token
num_workers: 1