defaults:
  - _self_

data_list:
  - multiwoz21_validation
  - iclr_2024_submissions_validation

language_model_list:
  - model-roberta-base_multiwoz21-train-10000_ftm-lora_r-8_alpha-16_lora-target-query_key_value_lora-dropout-0.01_rslora-True_5e-05-constant-0.01-50.yaml

layer_indices_list:
  - "[-1]"
  # - "[-2]"
  - "[-3]"
  # - "[-4]"
  - "[-5]"
  # - "[-6]"
  - "[-7]"
  # - "[-8]"
  - "[-9]"
  # - "[-10]"
  - "[-11]"
  # - "[-12]"

checkpoint_no_list:
  - 400
  # - 800
  - 1200
  # - 1600
  - 2000
  # - 2400
  - 2800
  # - 3200
  - 3600
  # - 4000
  - 4400
  # - 4800
  - 5200
  # - 5600
  - 6000
  # - 6400
  - 6800
  # - 7200
  - 7600
  # - 8000
  - 8400
  # - 8800
  - 9200
  # - 9600
  - 10000
  # - 10400
  - 10800
  # - 11200
  - 11600
  # - 12000
  - 12400
  # - 12800
  - 13200
  # - 13600
  - 14000
  # - 14400
  - 14800
  # - 15200
  - 15600

data_number_of_samples_list:
  - 3000

embeddings_data_prep_num_samples_list:
  - 30000

wandb_project: "Topo_LLM_pipeline_jobs"
