#data_name: data-multiwoz21_split-validation_ctxt-dataset_entry_samples-1000
data_name: data-iclr_2024_submissions_split-train_ctxt-dataset_entry_samples-1000

level_1: lvl-token
level_2: lvl-token

prefix_1: add-prefix-space-False_max-len-512
prefix_2: add-prefix-space-False_max-len-512


model_1: model-gpt2-medium_mask-no_masking
#model_1: model-roberta-base_mask-no_masking
#model_2: model-roberta-base_finetuned-on-multiwoz21-train_context-dialogue_mask-no_masking
#model_2: model-roberta-base_finetuned-on-sgd-train-10000_context-dialogue_mask-no_masking
#model_2: model-roberta-base_finetuned-on-multiwoz21_ftm-lora_mask-no_masking
model_2: model-gpt2-medium_finetuned-on-multiwoz21_ftm-standard_checkpoint-2000_mask-no_masking
#model_2: model-roberta-base_finetuned-on-multiwoz21_ftm-standard_overfitted_mask-no_masking

layer: -1

norm_1: norm-None
norm_2: norm-None

array_dir_1: array_dir
array_dir_2: array_dir

embedding_level_1: token_lvl
embedding_level_2: token_lvl
#embedding_level_1: sentence_lvl_mean
#embedding_level_2: sentence_lvl_mean
#embedding_level_1: cls_lvl
#embedding_level_2: cls_lvl

# default for embedding_level_1: token_lvl
samples_1: 10000
samples_2: 10000
#samples_1: 200000
#samples_2: 200000
# default for embedding_level_1: sentence_level, cls_level
#samples_1: 5000
#samples_2: 5000