defaults:
  - task_performance_analysis: default
  - _self_

investigate_distances:
  array_truncation_size: 5000

wandb_export:
  wandb_id: "[ANONYMIZED_WANDB_ID]"
  project_name: "[ANONYMIZED_PROJECT_NAME]"
  samples: 50000
  use_saved_concatenated_df: False
