defaults:
  - base_model@_here_: roberta-base_for_masked_lm
  - gradient_modifier: do_nothing
  - finetuning_datasets: train_and_eval_on_one-year-of-tsla-on-reddit
  - finetuning_parameters@_here_: default_parameters
  - ../tokenizer@tokenizer: basic_tokenizer
  - peft: standard
  - _self_
