defaults:
  - base_model: gpt2_for_causal_lm
  - batch_sizes: default
  - finetuning_datasets: train_and_eval_on_one-year-of-tsla-on-reddit_train-samples-small
  - finetuning_parameters@_here_: default_parameters
  - gradient_modifier: do_nothing
  - ../tokenizer@tokenizer: basic_tokenizer
  - trainer_modifier: add_wandb_callback
  - peft: standard
  - _self_
