pretrained_model_name_or_path: roberta-base
short_model_name: ${finetuning.pretrained_model_name_or_path}
max_length: 512
batch_sizes:
  - train: 8
  - eval: 16
finetuning_datasets: 
  train_dataset: ${data.multiwoz21_train_5000}
  eval_dataset: ${data.multiwoz21_validation_5000}