defaults:
  # - peft: standard
  - peft: lora
  - finetuning_datasets: train_and_eval_on_bbc
  # - finetuning_datasets: train_and_eval_on_bbc_manual
  - finetuning_parameters@_here_: default_parameters
  - _self_

pretrained_model_name_or_path: roberta-base
short_model_name: ${finetuning.pretrained_model_name_or_path}