lm_mode: clm
pretrained_model_name_or_path: gpt2-medium
short_model_name: ${finetuning.base_model.pretrained_model_name_or_path}
task_type: causal_lm
tokenizer_modifier:
  mode: add_padding_token
  padding_token: "<|pad|>"