lm_mode: MLM
pretrained_model_name_or_path: roberta-base
short_model_name: ${finetuning.base_model.pretrained_model_name_or_path}
task_type: TOKEN_CLASSIFICATION
tokenizer_modifier:
  mode: DO_NOTHING
  padding_token: "<pad>"