# TODO: Edit this for token classification

lm_mode: MLM
pretrained_model_name_or_path: roberta-base
short_model_name: ${finetuning.pretrained_model_name_or_path}
tokenizer_modifier:
  mode: DO_NOTHING
  padding_token: "<pad>"