defaults:
  - data: bbc
  - embeddings: roberta
  - transformations: none
  - _self_

data_dir: data
seed: 1234

hydra:
  run:
    dir: experiments/${embeddings.huggingface_model_name}/${now:%Y-%m-%d_%H-%M-%S}