defaults:
  # - data: bbc
  #- data: iclr_2024_submissions
  - data: multiwoz21_train_5000
  #- data: sgd
  #- data: wikitext
  - embeddings: basic_embeddings
  - finetuning: roberta-base_tuning
  - paths: absolute_repository_base
  # - storage: zarr_vectors_xarray_metadata
  - storage: zarr_vectors_pickle_metadata
  - transformations: none
  - override hydra/job_logging: custom
  - _self_


seed: 1234
verbosity: 1
preferred_torch_backend: auto

#------------------------- Hydra Config ------------------------#
hydra:
  run:
    dir: ${paths.repository_base_path}/hydra_output_dir/experiments/${embeddings.language_model.short_model_name}/${now:%Y-%m-%d_%H-%M-%S}
  job:
    chdir: False
    env_set:
      # HYDRA_FULL_ERROR: 1 # NOTE: This will not work for setting the environment variable, set in code instead
      CUDA_VISIBLE_DEVICES: 0