defaults:
  - analysis: default
  - data: one-year-of-tsla-on-reddit
  - embeddings_data_prep: default
  - embeddings: basic_embeddings
  - feature_flags: default
  - finetuning: finetuning_for_masked_lm
  - inference: default
  - language_model: roberta-base
  - local_estimates: twonn
  - paths: absolute_repository_base
  - storage: default
  - tokenizer: basic_tokenizer
  - transformations: none
  - wandb: default
  - override hydra/job_logging: custom
  - _self_

n_jobs: 1
global_seed: 1111 # The main_config global_seed is currently rarely used, as we have separate seeds for the subsampling and finetuning.
verbosity: 1
preferred_torch_backend: auto

#------------------------- Hydra Config ------------------------#
# Instructions for setting up the output directory paths:
# https://hydra.cc/docs/configure_hydra/workdir/
#
# Workaround for taking care of slashes '/' in 'hydra.job.override_dirname'
# by adding an OmegaConf resolver 'sanitize_override_dirname':
# https://github.com/facebookresearch/hydra/discussions/2409
#
# Note that %Z (for the time zone) does not appear to work in the 'now' handler function

hydra:
  run:
    dir: ${paths.repository_base_path}/hydra_output_dir/run/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}/${sanitize_override_dirname:${hydra.job.override_dirname}}/seed=${global_seed}/
  sweep:
    dir: ${paths.repository_base_path}/hydra_output_dir/multirun/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}/
    subdir: ${sanitize_override_dirname:${hydra.job.override_dirname}}/seed=${global_seed}
  job:
    chdir: False
    env_set:
      # HYDRA_FULL_ERROR: 1 # Note: This will not work for setting the environment variable, set in code instead
      # CUDA_VISIBLE_DEVICES: 0
      OC_CAUSE: "1"
      PLACEHOLDER_ENV_VAR: "placeholder_value" # Note: This is here so that the 'env_set' key is not empty
    config:
      override_dirname:
        exclude_keys:
          - global_seed