defaults:
  - data: bbc
  - embeddings: roberta
  - paths: absolute_repository_base
  - transformations: none
  - _self_


seed: 1234
verbosity: 1

hydra:
  run:
    dir: ${paths.repository_base_path}/hydra_output_dir/experiments/${embeddings.huggingface_model_name}/${now:%Y-%m-%d_%H-%M-%S}
  job:
    chdir: False