defaults:
  - _self_

analysis:
  create_plots_in_local_estimates_worker: false

compute_and_store_embeddings:
  skip_compute_and_store_embeddings: false

embeddings_data_prep:
  add_additional_metadata: true

finetuning:
  skip_finetuning: false
  do_create_finetuned_language_model_config: true

wandb:
  use_wandb: true