defaults:
  - _self_

analysis:
  create_plots_in_local_estimates_worker: false
  compare_sampling_methods:
    do_iterate_all_partial_search_base_directories: true
    do_analysis_influence_of_local_estimates_n_neighbors: true
    do_create_boxplot_of_mean_over_different_sampling_seeds: true
    do_noise_analysis: true
    do_checkpoint_analysis: true
    do_data_subsampling_number_of_samples_analysis: true

comparison:
  do_comparison_of_local_estimates: true

compute_and_store_embeddings:
  skip_compute_and_store_embeddings_in_pipeline: false

embeddings_data_prep:
  skip_embeddings_data_prep_in_pipeline: false
  add_additional_metadata: true

finetuning:
  skip_finetuning: false
  do_create_finetuned_language_model_config: true

scripts:
  dry_run: false

task_performance_analysis:
  plotting_create_distribution_plots_over_model_checkpoints: true
  plotting_create_distribution_plots_over_model_layers: true

wandb:
  use_wandb: true