#!/bin/bash

# This script sets symbolic links form the project directory to the HPC cluster scratch drive from intermediate data directories in our local topological features computation.
# This data does not necessarily need to be backed up, so we can save space on the GPFS project directories by moving it to the scratch drive.
# In addition, this avoids problems with our local backup, which is not able to handle the large amount of data generated by the topological features computation on the project directories.

# Notes:
# - This needs to be run on the HPC cluster cluster.
# - Make sure the link_name does not exist yet, otherwise the command will place the link inside the existing directory.

# Syntax: ln -s <target> <link_name>

TARGET="/gpfs/scratch/${USER}/git-source/Topo_LLM/data/analysis/prepared"
LINK_NAME="/gpfs/project/${USER}/git-source/Topo_LLM/data/analysis/prepared"

# Check if the link name already exists
if [ -e "${LINK_NAME}" ]; then
    echo "@@@ The link name LINK_NAME=${LINK_NAME} already exists. Please remove it first."
    exit 1
fi

ln -s "${TARGET}" "${LINK_NAME}"

echo ">>> Symbolic link created from TARGET=${TARGET} to LINK_NAME=${LINK_NAME}."

echo ">>> Script finished."
# Exit with the return code of the last command
exit $?
